src/main/java/controller/AccountsController.java
package controller;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

import model.User;
import service.UserSessionBean;
import util.Resources;

/**
 * <p>Handles all of the logic for user accounts and security.</p> 
 * <p>Login, logout, and register user methods.</p>
 * <p>Methods for JSF pages, get current user, test if the user is an admin or not.</p>
 * <p>Methods for handling user details and password updates.</p>
 * <p>Administrator methods for promoting and deleting users.</p>
 * <p>JSF utility to see if a component has been set to an error state.</p>  
 * 
 * @author Karl Nicholas
 *
 */
@ManagedBean
public class AccountsController {
    @Inject private FacesContext facesContext;
    @Inject private UserSessionBean userService;
    private static final String NAV_ACCOUNTS = "/views/accounts/accounts.xhtml";
    private static final String NAV_ACCOUNTS_REDIRECT = "/views/accounts/accounts.xhtml?faces-redirect=true";

    private String email;
    private String password;

    private User newUser;
    private User currentUser;

    private String passwordConfirmation;
    
    @PostConstruct
    public void postConstruct() {
        ExternalContext externalContext = facesContext.getExternalContext();
        currentUser = (User)externalContext.getSessionMap().get("user");
        // in case went to a specific URL
        if ( currentUser == null ) {
            HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
            java.security.Principal principal = request.getUserPrincipal();
            if ( principal != null ) {
                try {
                	currentUser = userService.findByEmail(principal.getName());
                } catch (Exception ignored) {
                    // logout whoever and set user to null.
                    try {
                        ((HttpServletRequest) externalContext.getRequest()).logout();
                    } catch (ServletException alsoIgnored) {}
                    externalContext.invalidateSession();
                    currentUser = null;
                }
            }
        }
        newUser = new User();
    }

	/**
	 * True if a user is logged in.
	 * 
	 * @return True if Logged In
	 */
	public boolean isLoggedIn() {
	    return currentUser != null;
	}
	
	/**
	 * True if a user has the ADMIN role.
	 * 
	 * @return True if ADMIN
	 */
	public boolean isAdmin() {
	    if ( currentUser == null ) return false;
	    return currentUser.isAdmin();
	}
	
	/**
	 * Currently logged user or null.
	 *  
	 * @return User
	 */
	public User getCurrentUser() {
	    return currentUser;
	}
	

    /**
     * Login a user using the email and password fields.
     * 
     * @return String navigation to /views/accounts/accounts.xhtml
     */
    public String login() {
        ExternalContext externalContext = facesContext.getExternalContext();
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
        if ( request.getUserPrincipal() == null ) {
            try {
            	// Ignorecase is handled by the database, see create.sql.
                request.login(email, password);
                currentUser = userService.findByEmail(email);
                externalContext.getSessionMap().put("user", currentUser);                
            } catch (ServletException ignored) {
                // Handle unknown username/password in request.login().
                facesContext.addMessage(null, new FacesMessage("Login Failed!", ""));
                return null;
            }
        } 
        return NAV_ACCOUNTS_REDIRECT;
    }

    /**
     * Email Field
     * @return Email field.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Email Field
     * @param email field.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Password Field
     * @return Password field.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Password Field
     * @param password field.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Logout current user
     * 
     * @return Naviation to /views/accounts/accounts.xhtml
     */
    public String logout() {
        ExternalContext externalContext = facesContext.getExternalContext();
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
        try {
            request.logout();
            externalContext.invalidateSession();
        } catch (ServletException e) {
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Logout Failed!", Resources.getRootErrorMessage(e) ));
            return null;
        }
        // navigate
        return NAV_ACCOUNTS_REDIRECT;
    }

    /**
     * Register a new user
     * 
     * @return String navigation to /views/accounts/accounts.xhtml
     */
    public String register() {
        try {
            // save the password before encoding
            String password = newUser.getPassword();
            currentUser = userService.encodeAndSave(newUser);
            if ( currentUser == null ) {
                facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Registration failed!", "User Already Exists" ));
                return null;
            } else {
                // login user            
                ExternalContext externalContext = facesContext.getExternalContext();
                HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
            	// Ignorecase is handled by the database, see create.sql.
                request.login(newUser.getEmail(), password);
                externalContext.getSessionMap().put("user", currentUser);
            }
        } catch (Exception e) {
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Registration failed!", Resources.getRootErrorMessage(e) ));
            return null;
        }
        // navigate
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Registration Successful!", "" ));
        return NAV_ACCOUNTS;
    }

    /**
     * New User Field
     * @return newUser field.
     */
    public User getNewUser() {
        return newUser;
    }
    /**
     * New User Field
     * @param newUser field.
     */
    public void setNewUser(User newUser) {
        this.newUser = newUser;
    }

    /**
     * Check user.password against passwordConfirmation, encode password, and merge user.
     * @return String navigation to /views/accounts/accounts.xhtml
     */
    public String updatePassword() {
        try {
            // check password confirmation.
            if ( !currentUser.getPassword().equals(passwordConfirmation) ) {
                facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Passwords Must Match", ""));
                return null;
            }
            // update user
            userService.merge(userService.updatePassword(currentUser));
        } catch (Exception e) {
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Update failed", Resources.getRootErrorMessage(e)));
            return null;
        }
        // message and navigation
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Password Updated", ""));
        return NAV_ACCOUNTS;
    }

    /**
     * Password Confirmation Field
     * @return passwordConfirmation field.
     */
    public String getPasswordConfirmation() {
        return passwordConfirmation;
    }

    /**
     * Password Confirmation Field
     * @param passwordConfirmation field.
     */
    public void setPasswordConfirmation(String passwordConfirmation) {
        this.passwordConfirmation = passwordConfirmation;
    }

    /**
     * Update/merge user fields
     * @return Navigation to /views/accounts/accounts.xhtml
     */
    public String update() {
        try {
            // update user
            userService.merge(currentUser);
        } catch (Exception e) {
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Update unsuccessful", Resources.getRootErrorMessage(e)));
            return null;
        }
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "User Info Updated", ""));
        return NAV_ACCOUNTS;
    }

    /**
     * Return a list of users
     * @return List of users
     */
    public List<User> getUsers() {
        return userService.findAll();
    }

    /**
     * Remove a user based on id.
     * @param id of User to be removed.
     */
    public void removeUser(Long id) {
        if ( currentUser.getId() == id ) throw new RuntimeException("Cannot change current user!");
        userService.delete(id);
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "User removed", "") );
    }

    /**
     * Promote user to administrator based on id
     * @param id of User to be promoted.
     */
    public void promoteUser(Long id) {
        if ( currentUser.getId() == id ) return;
        userService.promoteUser(id);
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "User promoted to administrator", "") );
    }

    /**
     * Demote a user, based on id, by removing ADMIN role.
     * @param id of User to be demoted. 
     */
    public void demoteUser(Long id) {
        if ( currentUser.getId() == id ) return;
        userService.demoteUser(id);

src/main/webapp/views/accounts/accounts.xhtml
<ui:composition template="/views/template/template.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui">
<ui:define name="title"><h:outputText value="Java EE MVC - User Account"/></ui:define>
<ui:define name="content">
<ui:fragment rendered="#{!accountsController.loggedIn}">
  <ui:include src="/views/accounts/loginsignup.xhtml" />
</ui:fragment>
<ui:fragment rendered="#{accountsController.loggedIn}">
  <ui:include src="/views/accounts/user/userdetail.xhtml" />
</ui:fragment>
</ui:define>
</ui:composition>

src/main/webapp/views/accounts/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <link rel="stylesheet" type="text/css" media="all" href="#{request.contextPath}/webjars/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <title><ui:insert name="title"><h:outputText value="Java EE MVC - Login Required" /></ui:insert></title>
</h:head>
<h:body>
<div class="container-fluid example2">
<ui:insert name="header"><ui:include src="/views/template/header.xhtml" /></ui:insert>
<h:form id="loginForm" onsubmit="document.getElementById('loginForm').action='j_security_check';" prependId="false" styleClass="form-horizontal">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"><h:outputText value="Login Required" styleClass="control-label"/></div>
  </div>
  <div class="form-group">
    <h:outputLabel for="j_username" value="Email: " styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputText id="j_username" name="j_username" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <h:outputLabel for="j_password" value="Password: " styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputSecret id="j_password" name="j_password" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"><h:commandButton id="submit" value="Login" styleClass="btn btn-default" /></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"><h:outputLabel rendered="#{not empty param['Retry']}" value="Login Failed. Please try again." /></div>
  </div>
</h:form>
</div>
<!-- jQuery first, then Bootstrap JS. -->
<script src="#{request.contextPath}/webjars/jquery/1.11.1/jquery.min.js" type="text/javascript"/>
<script src="#{request.contextPath}/webjars/bootstrap/3.3.7/js/bootstrap.min.js" type="text/javascript"/>
</h:body>
</html>

src/main/webapp/views/accounts/loginsignup.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://xmlns.jcp.org/jsf/passthrough">  
<h:form id="loginsignupForm" styleClass="form-horizontal">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"><h:outputText value="Login or Register" styleClass="control-label"/></div>
  </div>
  <div class="form-group">
    <h:outputLabel for="email" value="Email:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputText id="email" value="#{accountsController.email}" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <h:outputLabel for="password" value="Password:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputSecret id="password" value="#{accountsController.password}" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2"><h:commandButton id="login" action="#{accountsController.login()}" value="Login" styleClass="btn btn-default"/></div>
    <div class="col-sm-2"><h:button id="toRegister" outcome="/views/accounts/register.xhtml" value="Register" styleClass="btn"/></div>
  </div>
  <div class="form-group">
    <h:messages p:name="loginsignupForm:messages" globalOnly="true" showDetail="true" styleClass="col-sm-offset-2 col-sm-4"/>
  </div>
</h:form>
</f:view>

src/main/webapp/views/accounts/register.xhtml
<ui:composition template="/views/template/template.xhtml"
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
<ui:define name="title"><h:outputText value="Java EE MVC - Register" /></ui:define>
<ui:define name="content">
<h:form id="registerForm" styleClass="form-horizontal">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4"><h:outputText value="Register" styleClass="control-label"/></div>
  </div>
  <div class="form-group #{accountsController.isValid('registerForm:email')?'':'has-error'}">
    <h:outputLabel for="email" value="Email:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputText id="email" value="#{accountsController.newUser.email}" styleClass="form-control" p:aria-describedby="registerForm:helpforemail"/>
      <h:message id="helpforemail" styleClass="help-block" for="email"/>
    </div>
  </div>
  <div class="form-group #{accountsController.isValid('registerForm:password')?'':'has-error'}">
    <h:outputLabel for="password" value="Password:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputSecret id="password" value="#{accountsController.newUser.password}" styleClass="form-control" p:aria-describedby="registerForm:helpforpassword"/>
      <h:message id="helpforpassword" styleClass="help-block" for="password"/>
    </div>
  </div>
  <div class="form-group">
    <h:outputLabel for="firstName" value="First Name:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputText id="firstName" value="#{accountsController.newUser.firstName}" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <h:outputLabel for="lastName" value="Last Name:" styleClass="col-sm-2 control-label"/>
    <div class="col-sm-4"><h:inputText id="lastName" value="#{accountsController.newUser.lastName}" styleClass="form-control"/></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2"><h:commandButton id="register" action="#{accountsController.register()}" value="Register" class="btn btn-default"/></div>
    <div class="col-sm-2"><h:button outcome="/views/accounts/accounts.xhtml" value="Cancel" class="btn"/></div>
  </div>
  <div class="form-group">
    <h:messages globalOnly="true" showDetail="true" styleClass="col-sm-offset-2 col-sm-4" />
  </div>
</h:form>
</ui:define>
</ui:composition>